/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author John Rey
 */
public class Appointment extends javax.swing.JFrame {

    

    /**
     * Creates new form Appointment
     */
    public Appointment() {
        initComponents();
        setLocationRelativeTo(null);
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new java.awt.TextField();
        typee = new javax.swing.JComboBox();
        pass_appoint = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        amount = new java.awt.TextField();
        testype = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        datee = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 250, 30));

        typee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Bank Transfer", "Gcash", "Express" }));
        typee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeeActionPerformed(evt);
            }
        });
        getContentPane().add(typee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 140, 30));
        getContentPane().add(pass_appoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 130, 30));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 70, 30));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 70, 30));

        amount.setEditable(false);
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 109, 30));

        testype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Drug Test", "DNA Test", "Urine/Stool Test", "Blood Test", "Covid Test" }));
        testype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testypeMouseClicked(evt);
            }
        });
        testype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testypeActionPerformed(evt);
            }
        });
        getContentPane().add(testype, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 150, 30));

        jButton3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton3.setText("RESET");
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 342, 80, -1));

        datee.setDateFormatString("MM dd, yyyy");
        getContentPane().add(datee, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logins/Appointment.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Medic", "root","");

            String query ="INSERT into appoint(name,typetest,amount,date,payment,status,password) "
            + "values(?,?,?,?,?,?,?)";
            
           
            PreparedStatement pst= con.prepareStatement(query);

                String value1=testype.getSelectedItem().toString();
                String value2= typee.getSelectedItem().toString();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String value3=sdf.format(datee.getDate());
                
                pst.setString(1, name.getText());
                pst.setString(2, value1); 
                pst.setString(3, amount.getText());
                pst.setString(4, value3);
                pst.setString(5,value2);
                pst.setString(7, pass_appoint.getText());
                pst.setString(6,"Unpaid");
                pst.executeUpdate();
               
                
                
                
                //Password Verification dito//
                String sql = "Select *from appoint where password=?";
            PreparedStatement passpst = con.prepareStatement(sql);
            
            passpst.setString(1, pass_appoint.getText());
            ResultSet rs= passpst.executeQuery();
            if (rs.next()){
                JOptionPane.showMessageDialog(null,"Success! You can now pay in the Menu");
                
                
                
              
                Main menu = new Main();
                menu.setVisible(true);
                this.setVisible(true);
                this.setVisible(false);
                
                
             
            
        
        }}
    
        catch(ClassNotFoundException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
            
            

        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void typeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeeActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void testypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testypeActionPerformed
        // TODO add your handling code here:
        try{
            String a="Drug Test";
            String b="DNA Test";
            String c="Urine/Stool Test";
            String d="Blood Test";
            String e="Covid Test";
            if (testype.getSelectedItem() == a){
                amount.setText("1000");}
            else if(testype.getSelectedItem() == b){
                amount.setText("2000");}
            else if(testype.getSelectedItem() == c){
                amount.setText("3000");}
            else if(testype.getSelectedItem() == d){
                amount.setText("4000");}
            else  {
                amount.setText("5000");
            }

        }catch(Exception e){}

    }//GEN-LAST:event_testypeActionPerformed

    private void testypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testypeMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_testypeMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField amount;
    private com.toedter.calendar.JDateChooser datee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private java.awt.TextField name;
    private javax.swing.JPasswordField pass_appoint;
    private javax.swing.JComboBox testype;
    private javax.swing.JComboBox typee;
    // End of variables declaration//GEN-END:variables
}
