/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;


import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;

/**
 *
 * @author John Rey
 */

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
         
        
        initComponents();
       

        setLocationRelativeTo(null);
        history.setCursor(new Cursor(Cursor.HAND_CURSOR));
        history.addMouseListener(new MouseAdapter() {
 
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Transactions tran= new Transactions();
                    tran.setVisible(true);
                    setVisible(false);
                } catch (Exception d) {
                    d.printStackTrace();
                }
            }});
         About.setCursor(new Cursor(Cursor.HAND_CURSOR));
        About.addMouseListener(new MouseAdapter() {
 
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    About tran= new About();
                    tran.setVisible(true);
                    setVisible(false);
                } catch (Exception d) {
                    d.printStackTrace();
                }
            }});
        Contact.setCursor(new Cursor(Cursor.HAND_CURSOR));
        Contact.addMouseListener(new MouseAdapter() {
 
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Contact tran= new Contact();
                    tran.setVisible(true);
                    setVisible(false);
                } catch (Exception d) {
                    d.printStackTrace();
                }
            }});
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
        logout.addMouseListener(new MouseAdapter() {
 
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Login tran= new Login();
                    tran.setVisible(true);
                    setVisible(false);
                } catch (Exception d) {
                    d.printStackTrace();
                }
            }});
 
    
        
        
    }
   
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        Appointment = new javax.swing.JButton();
        About = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        history = new javax.swing.JLabel();
        EditProfile = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        template = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Appointment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Appointment.setContentAreaFilled(false);
        Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(Appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 350, 40));
        getContentPane().add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 60, 20));
        getContentPane().add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 10));
        Contact.getAccessibleContext().setAccessibleName("Contact/Email");

        logout.setBorder(null);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, 20));
        getContentPane().add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 10));
        getContentPane().add(EditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, 10));
        getContentPane().add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 20));

        template.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logins/main.jpg"))); // NOI18N
        template.setOpaque(true);
        getContentPane().add(template, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        setSize(new java.awt.Dimension(1006, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentActionPerformed
        // TODO add your handling code here:
        Appointment app = new Appointment();
        app.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AppointmentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login app = new Login();
        app.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JButton Appointment;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel EditProfile;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel history;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel template;
    // End of variables declaration//GEN-END:variables

   
}

