/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author John Rey
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accnum = new java.awt.TextField();
        accname = new java.awt.TextField();
        acctype = new javax.swing.JComboBox();
        amnt = new java.awt.TextField();
        pass_pay = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnumActionPerformed(evt);
            }
        });
        getContentPane().add(accnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 410, 33));
        getContentPane().add(accname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 410, 33));

        acctype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bank Transfer", "Gcash", " Express" }));
        getContentPane().add(acctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 130, 30));

        amnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amntActionPerformed(evt);
            }
        });
        getContentPane().add(amnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 260, 30));
        getContentPane().add(pass_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 150, 30));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 100, 20));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 100, 20));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 70, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logins/Payment.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Medic", "root","");

            String query ="INSERT into payment_table(acc_number,acc_name,acc_type,amount,password) "
            + "values(?,?,?,?,?)";
            
           
            PreparedStatement pst= con.prepareStatement(query);
            pst.setString(1, accnum.getText());
            pst.setString(2, accname.getText());
            pst.setString(3, acctype.getSelectedItem().toString());
            pst.setString(4, amnt.getText());
            pst.setString(5, pass_pay.getText());
           
            

                //Password Verification dito//
            String sql = "Select * from appoint where password=?";
            PreparedStatement passpst = con.prepareStatement(sql);           
            passpst.setString(1, pass_pay.getText());
            ResultSet rs= passpst.executeQuery();
            if (rs.next()){
                String pay ="paid";
                String pass= pass_pay.getText(); 
                String stat= "UPDATE appoint SET status='"+pay+"' WHERE password='"+pass+"'  ";
                PreparedStatement statup = con.prepareStatement(stat);
                
                
                
                
                String paids="Unpaid";
                String foramount = "SELECT * from appoint WHERE password='"+pass+"' and status='"+paids+"' ";
                Statement st= con.createStatement();
                ResultSet amountrs = st.executeQuery(foramount); 
                amountrs.next();
                String status = amountrs.getString("status");
                
                
                
                
                
                int a =amountrs.getInt("amount");
                int b = Integer.parseInt(amnt.getText());
                
                
                
                if (a > b ){JOptionPane.showMessageDialog(null,"Payment is not enough ");
                amnt.setText("");}
                
                
                else{
                statup.execute();
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Payment Succesfull!");
                Main menu = new Main();
                menu.setVisible(true);
                this.setVisible(true);
                this.setVisible(false);}}
            
            
            
            
            
            
            
            
            
            else{
                JOptionPane.showMessageDialog(null,"ERROR! or The Transaction is Already Paid");
            
            }
        
        
        
        }
    
        catch(ClassNotFoundException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
            
            

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        main.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void accnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnumActionPerformed

    private void amntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amntActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     accnum.setText(" ");
          accname.setText("");
        
            amnt.setText("");
             pass_pay.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField accname;
    private java.awt.TextField accnum;
    private javax.swing.JComboBox acctype;
    private java.awt.TextField amnt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pass_pay;
    // End of variables declaration//GEN-END:variables
}
